command_line:
  - sensor:
      name: Rappel Conso Ciblé
      command: "python3 /config/rappelConsoHA/rappel_script.py /config/rappelConsoHA/mots_cles.txt"
      value_template: "{{ value_json.count }}"
      json_attributes:
        - data
        - nouveaux
        - new_count
        - keywords_used
        - last_update
        - error
      scan_interval: 14400
      command_timeout: 30

template:
  - sensor:
      - name: "Rappel Conso Nouveaux"
        state: "{{ state_attr('sensor.rappel_conso_cible', 'new_count') | default(0) }}"
        icon: >-
          {% if states('sensor.rappel_conso_nouveaux') | int > 0 %}
            mdi:alert-decagram
          {% else %}
            mdi:shield-check
          {% endif %}
        attributes:
          nouveaux: "{{ state_attr('sensor.rappel_conso_cible', 'nouveaux') }}"
